### ISSUE TITLE
Add count mechanisms

### ISSUE THREAD

**Issue by CarstVaartjes** [visualfabriq/bquery#10]
*Count*
A variation on sum, where you do +1 for each occurrence

*Count_NA*
A variation on sum_na, where you do +1 for each occurrence when the value != na

*Sorted_count_distinct*
This is another variation, where you need to have next to the result array also a work array (which should start with 0 or –1 values or something, as the factorized group always start at 0 or 1 right?) where you do the following:
- i is the current group row index in the result row (if you do not remember, look at how sum works with adding values to an array)
- If the current_value is different than work_array[i]:
    - do +1 for the result_array[i] 
    - set work_array[i] to the current value

The thing about it being "sorted_count_distinct" is that it assumes the column to have been pre-sorted (handy for POS-analytics situations). Later on we should add a general count_distinct, but this is higher priority for now

**Comment by CarstVaartjes** [comment]
They work, but need a slightly different calling  method to be more versatile (i'll explain next week).
That + product association + the "unique" (distinct) function (i've added that now) -> version 0.2

**Comment by FrancescElies** [comment]
Fine, let's discuss it

**Comment by CarstVaartjes** [comment]
These are in
