### ISSUE TITLE
Error installing bquery

### ISSUE THREAD

**Issue by dataisle** [visualfabriq/bquery#14]
when installing on mac osx using:
```python
python setup.py install 
```
i get the following error for Cython compilation:

```
bquery/ctable_ext.pyx:586:15: 'carray' is not a type identifier

error: Command "gcc -fno-strict-aliasing -I/Applications/Anaconda/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Ibquery -I/Applications/Anaconda/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Applications/Anaconda/anaconda/include/python2.7 -c bquery/ctable_ext.c -o build/temp.macosx-10.5-x86_64-2.7/bquery/ctable_ext.o" failed with exit status 1
``

**Comment by CarstVaartjes** [comment]
@FrancescElies do you have an idea?

**Comment by FrancescElies** [comment]
I agree, I think this could be related to bcolz pxd file not being found, did you installed it directly using ```python setup.py install```? Have you tried follwing the build section from the readme file?

```
git clone https://github.com/blosc/bcolz.git
cd bcolz
python setup.py build_ext --inplace
cd ..
export PYTHONPATH=$(pwd)/bcolz:${PYTHONPATH}

python setup.py build_ext --inplace
```

**Comment by dataisle** [comment]
i installed bcolz with conda and i believe its the most upto date version.
```
In [1]: import bcolz

In [2]: bcolz.__version__
Out[2]: '0.8.0'
```

i have tried the build as well and that fails with a similar error.

**Comment by FrancescElies** [comment]
I have the feeling that conda does not ship with the pxd file, would it be possible for you to locate where the bcolz files are and check if the pxd file is in place?

If the file is not there I would suggest as a quick and dirty solution to copy it there manually, as you see here https://groups.google.com/forum/#!topic/bcolz/vnilWfzZqlo we are checking how to overcome a similar problem

**Comment by dataisle** [comment]
after copying the pxd files to 
```
/anaconda/pkgs/bcolz-0.8.0-np19py27_0/lib/python2.7/site-packages/bcolz/ 
```
i still get the same error. is there another location where i should be copying them?

**Comment by FrancescElies** [comment]
I think pyx files might also be missing
Could you please try to copy all pxd and pyx files from this link https://github.com/Blosc/bcolz/tree/master/bcolz
```
carray_ext.pxd
definitions.pxd
carray_ext.pyx
```

**Comment by dataisle** [comment]
still the same erorr after copying pyx and pxd files. should these files be with numpy?

```
bquery/ctable_ext.pyx:67:23: undeclared name not builtin: carray
building 'bquery.ctable_ext' extension
C compiler: gcc -fno-strict-aliasing -I/Applications/Anaconda/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

compile options: '-Ibquery -I/Applications/Anaconda/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Applications/Anaconda/anaconda/include/python2.7 -c'
gcc: bquery/ctable_ext.c
bquery/ctable_ext.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
#error Do not use this file, it is the result of a failed Cython compilation.
 ^
1 error generated.
bquery/ctable_ext.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
#error Do not use this file, it is the result of a failed Cython compilation.
 ^
1 error generated.
error: Command "gcc -fno-strict-aliasing -I/Applications/Anaconda/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Ibquery -I/Applications/Anaconda/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Applications/Anaconda/anaconda/include/python2.7 -c bquery/ctable_ext.c -o build/temp.macosx-10.5-x86_64-2.7/bquery/ctable_ext.o" failed with exit status 1
```

**Comment by FrancescElies** [comment]
Ups :/ I'm running out of ideas, maybe could you please try the following (with pxd and pyx files in the bcolz folder) write the following command in your terminal ```export PYTHONPATH=/anaconda/pkgs/bcolz-0.8.0-np19py27_0/lib/python2.7/site-packages/bcolz/ :$PYTHONPATH``` and try to compile again.

**Comment by dataisle** [comment]
no dice. i will keep on playing around with it.

**Comment by FrancescElies** [comment]
would it be an option for you to get a fresh installation with a virtual enviroment? This is the way we actually do it

**Comment by dataisle** [comment]
certainly, will it work with conda environments or just virtualenv?

**Comment by CarstVaartjes** [comment]
i have it running on my mac with conda, main thing is that i installed bcolz and bquery not through conda or pip but with git clone and building. a bit unfortunate i know, but it has to do with bcolz not having the pxd/pyx files available yet when being installed from pip/conda

**Comment by CarstVaartjes** [comment]
@dataisle Any news? If you conda install everything except for bcolz and bquery itself and use the install guide as on the main page here, it really should work.

**Comment by dataisle** [comment]
Sorry about not being able to follow-up on this. I am running into issues with installing bcolz as well and this time it gives me a header missing error on numpy. perhaps i need to compile numpy myself as well?

**Comment by CarstVaartjes** [comment]
The conda numpy was enough for me (osx 10.10.2 13" macbook pro) with the manual install of bcolz and bquery. Did you install the pre-requisites of bcolz with conda? (cython, numexpr, bottleneck?)

**Comment by dataisle** [comment]
yes, cythom numexpr etc are installed through conda? should i compile myself?

**Comment by FrancescElies** [comment]
I just had to install bquery, in case it helps see below typed commands (about compiling yourself those packages I believe it should not matter, but I´m not sure):
```
cd src
rm -rf bcolz
git clone https://github.com/blosc/bcolz.git
cd bcolz
python setup.py build_ext --inplace
python setup.py install
cd ..
export PYTHONPATH=$(pwd)/bcolz:${PYTHONPATH}
rm -rf bquery
git clone https://github.com/visualfabriq/bquery.git
cd bquery
python setup.py build_ext --from-templates --inplace
python setup.py install
```

**Comment by dataisle** [comment]
Sorry for being late. I was able to compile everything. i found that i needed to pip install numpy and not install it from conda from there on the above instructions worked. Also, i think Jinja2 requirement needs to be added to the requirement.txt file

**Comment by gopiks** [comment]
Hi, I have been trying to install bquery but it throws following error:
error: Don't know how to compile bquery/ctable_ext.pyx

I am using python 2.7 on windows 8
