### ISSUE TITLE
Automatic detection of dirty factorization cache

### ISSUE THREAD

**Issue by ARF1** [visualfabriq/bquery#18]
It would be nice to raise an error (or automatically recreate the factorization cache) if the database has changed since the cache was created.

I was thinking of hooking into `__setitem__` to detect changes while the database was loaded and e.g. looking at modification times of the bcolz files on disc to detect changes while program was off. Is this a reasonable approach?

**Comment by CarstVaartjes** [comment]
Hi,

Welcome and thanks for the input! :)
Good idea! we discussed this also a bit with the Bcolz creators. Some thoughts:
- a bcolz directory might be updated (appended, added columns, deleted columns) directly through bcolz and not bquery. in that case we cannot catch this and the user should be aware of this themselves
- this might lead to the cache being invalid or orphaned (in the case of a column having been deleted)
- we currently do not write bquery metadata yet (we directly check for the existence of rootdirs), but that could/should be improved to be honest
- in the case when all calls are done through bquery, we should add something to each method that upon completion updates (after data updates) or deletes (after a delcol) the factor and values carrays
- a way around it would be indeed (as you suggest) comparing the timestamps of the source column and the factor or value carray (but possibly not optimal, if for reasons other than a data change the timestamp might be altered)

I think the metadata + wrapping of bcolz with added caching consequences probably is the optimal solution, but maybe much more work than a timestamp comparison with nearly similar results. 
@esc do you have any ideas here?

**Comment by CarstVaartjes** [comment]
I've implemented the timestamp based solution #20 
How does this look to you? (still would have to look into the wrapping of append, delete, addcol and delcol in the future)

**Comment by CarstVaartjes** [comment]
Solved by #20
